// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateLease.Data;

#nullable disable

namespace RealEstateLease.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RealEstateLease.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Endereço")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Proprietario")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<double>("ValorDoAluguel")
                        .HasPrecision(10, 2)
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Imoveis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cep = "33845100",
                            Endereço = "Rua: Safira n° 352, Belo Horizonte - Mg",
                            Proprietario = "Alex",
                            Telefone = "31995654123",
                            ValorDoAluguel = 500.0
                        },
                        new
                        {
                            Id = 2,
                            Cep = "3392256",
                            Endereço = "Rua: Esmeralda n° 560, Contagem - Mg",
                            Proprietario = "Lily",
                            Telefone = "31955623789",
                            ValorDoAluguel = 800.0
                        },
                        new
                        {
                            Id = 3,
                            Cep = "75562456",
                            Endereço = "Rua: Calafates  n° 750, Diamantina - Mg",
                            Proprietario = "Joao",
                            Telefone = "33975645627",
                            ValorDoAluguel = 1100.0
                        },
                        new
                        {
                            Id = 4,
                            Cep = "55946023",
                            Endereço = "Rua: Tupi n° 955, Ribeirao das Neves - Mg",
                            Proprietario = "Elisa",
                            Telefone = "31995698123",
                            ValorDoAluguel = 1500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
